### ISSUE TITLE
Uncaught Error: Call to a member function get() on null

### ISSUE THREAD

**Issue by mickeysanga** [WPDevelopers/essential-addons-for-elementor-lite#745] opened 2023-05-11 15:29 UTC
Hi, we're experiencing the follow issue on our site...

Error Level: E_ERROR
Message: Uncaught Error: Call to a member function get() on null in wp-content/plugins/essential-addons-for-elementor-lite/includes/Classes/Elements_Manager.php:213

Stack trace:
#0 /wp-content/plugins/essential-addons-for-elementor-lite/includes/Classes/Elements_Manager.php(139): Essential_Addons_Elementor\Classes\Elements_Manager->save_widgets_list()
#1 /wp-content/plugins/essential-addons-for-elementor-lite/includes/Classes/Asset_Builder.php(120): Essential_Addons_Elementor\Classes\Elements_Manager->get_element_list()
#2 /wp-includes/class-wp-hook.php(308): Essential_Addons_Elementor\Classes\Asset_Builder->frontend_asset_load()
#3 /wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()

File: /wp-content/plugins/essential-addons-for-elementor-lite/includes/Classes/Elements_Manager.php
Line: 213
Request: /my-shop-account/?customize_changeset_uuid=b0fb47d6-93a9-4b72-8513-8d99ebaf8e64&customize_messenger_channel=preview-0

Looks like the $documents object isn't being checked for before one of its methods is being used in 'save_widgets_list()'. Other functions in the same file are checking that documents is an object first before attempting to use it.

Any help would be appreciated.

**Comment by rudlinkon** [comment] 2023-05-12 04:35
Thank you @mickeysanga for your attention. we are already aware of this issue and fixed it in our development branch. it will be published in the next release. so please be patient till then.
Ref: https://github.com/WPDevelopers/essential-addons-for-elementor-lite/blob/dev/includes/Classes/Elements_Manager.php#L213

**Comment by rudlinkon** [comment] 2023-05-29 18:01
The issue is fixed on `v5.7.3`
Feel free to reopen if having any issues.

**Closed by rudlinkon** 2023-05-29 18:01 UTC
