### ISSUE TITLE
Lightbox Modal button alightment always LEFT

### ISSUE THREAD

**Issue by ladirection** [WPDevelopers/essential-addons-for-elementor-lite#658] opened 2021-06-09 19:18 UTC
Hello, I'm running Elementor pro with EA pro on Hello theme, everything latest version with WP 5.7.2 and PHP 7.4

Someone just mentioned to me that all the Lightbox modal buttons on my site are suddenly no longer centered but all justified to the left. I tried creating a new page and dragging the lightbox modal widget into it and I can't get it to justify center or right. 

Is this a known issue? It must have crept up very recently as I demoed that page to someone last month and all was fine.

Thanks!

**Comment by abid112** [comment] 2021-06-10 11:05
Hi @ladirection ,

First of all, we're really sorry for the inconvenience.
Thanks for pointing out the issue. I already informed our dev team according to this. This will be fixed in the future release of Essential Addons for Elementor don't worry.

Thank you!

**Comment by abid112** [comment] 2021-06-13 11:58
Hi @ladirection , 

Well, It's not a bug actually! You need to regenerate your asset from **wp-admin -> Essential Addons** then, switch to the ‘**Tools**’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://d.pr/i/OeGVUT

Also, make sure to Regenerate Files from **wp-admin -> Elementor -> Tools** as well. Check out this screenshot: https://d.pr/i/23N5eb

It should be fine.
Let me know how it goes!

**Closed** 2021-06-21 06:14 UTC
