### ISSUE TITLE
plugin has compatibility issue with elementor 3.7+

### ISSUE THREAD

**Issue by MaxBoyman** [WPDevelopers/essential-addons-for-elementor-lite#734] opened 2022-08-18 06:07 UTC
There is an important problem with this plugin which in the following scenario will cause elementor paste style button not working properly:
-when elementor 3.7+ and elementor pro 3.7+ has been installed
-when essential-addons-for-elementor installed
in this case when a user is editing either a page or a post and you use paste style button to copy and paste an style to another element the update button will be green but won't work.

**Comment by khan-rafin-ahmed** [comment] 2022-08-18 07:12
Hi @MaxBoyman,

I have tried to reproduce this already from our end as well but seems to be working as expected.

Can you please check for plugin conflicts by deactivating all the plugins except for Essential Addons & Elementor?

If you are still seeing errors, please show the console error that you are getting. You can also contact our support here for further information: https://wpdeveloper.com/support/new-ticket/

Thank you!

**Comment by MaxBoyman** [comment] 2022-08-18 17:07
Hi,
It seems that the problem is with conditional display feature. when i turned it off the problem was fixed. also when i downgrade elementor to 3.6.8 problem fixed in some scenarios but sometimes it is there.

**Comment by rudlinkon** [comment] 2022-08-19 02:39
Hi @MaxBoyman,
Thank you for your information, we reproduce the issue and already fixed it on our dev version, and will be released soon.

**Comment by abid112** [comment] 2023-01-03 05:56
Hi @MaxBoyman , we've fixed the issue that you reported and I can assure you that, Essential Addons for Elementor is compatible with the latest **Elementor 3.9.2**

I'm closing this issue as resolved!

**Closed by abid112** 2023-01-03 05:56 UTC
Labels: bug
